name: cpp_lib_env
channels:
  - conda-forge
dependencies:
  - gcc=14.2.0
  - gxx=14.2.0
  - cmake=3.30.5
  - hdf5=1.14.3
  - libnetcdf=4.9.2
  - netcdf4=1.7.1
  - python=3.12.7
  - numpy=1.26.4
  - pandas=2.2.3
